name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Using Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    # Use this GitHub Action
    - name: Check package version
      uses: technote-space/package-version-check-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_DISABLED: 1
    - name: setup github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: npm publish
      run: |
        npm version patch
        npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
